spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #applicaiton 로딩시점에 drop 후 create applicaiton이 끝나도 db에 남아있음.
    properties:
      hibernate:
        format_sql: true
      #쿼리가 한줄로 나오는게 아니라 포맷팅이 되어 이쁘게 나올수 있도록 해줌.
       # show_sql: true  콘솔에 찍는 방법이라서 이것보단 아래의 log로 남기자
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 1000
        one-indexed-parameters: true


logging.level:
  org.hibernate.SQL: debug #콘솔에 남기는게 아니라 로그파일로 남길 수 있음.
  #org.hibernate.type: trace #파라미터 바인딩된 파라미터까지 볼 수 있음.
